[workspace]
members = [
    "edgedb-errors",
    "edgedb-derive",
    "edgedb-protocol",
    "edgedb-client",
    "edgedb-tokio",
    "examples/globals",
    "examples/query-error",
]

[profile.release]
debug = true
lto = true
